In [1]:
import pandas as pd
data={
    "Tid":[1,2,3,4,5,6,7,8,9,10],
    "Refund":["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "Marital Status":["Single","Married","Single","Married","Divorced",
                        "Married","Divorced","Single","Married","Single"],
    "Taxable Income":["125K","100K","70K","120K","95K",
                        "60K","220K","85K","75K","90K"],
    "Cheat":["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}
df=pd.DataFrame(data)
df.set_index("Tid", inplace=True)

In [2]:
df.iloc[[0,4,7,8]]

    Refund Marital Status Taxable Income Cheat
Tid
1      Yes         Single           125K    No
5       No       Divorced            95K   Yes
8       No         Single            85K   Yes
9       No        Married            75K    No

In [3]:
df.iloc[3:7]

    Refund Marital Status Taxable Income Cheat
Tid
4      Yes        Married           120K    No
5       No       Divorced            95K   Yes
6       No        Married            60K    No
7      Yes       Divorced           220K    No

In [4]:
df.iloc[4:8,2:4]

    Taxable Income Cheat
Tid
5              95K   Yes
6              60K    No
7             220K    No
8              85K   Yes

In [5]:
df.iloc[:,1:4]

    Marital Status Taxable Income Cheat
Tid
1           Single           125K    No
2          Married           100K    No
3           Single            70K    No
4          Married           120K    No
5         Divorced            95K   Yes
6          Married            60K    No
7         Divorced           220K    No
8           Single            85K   Yes
9          Married            75K    No
10          Single            90K   Yes

In [7]:
iris_df=pd.read_csv("Iris.csv")
print(iris_df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
iris_dropped=iris_df.drop(index=4)                     
iris_dropped=iris_dropped.drop(columns=iris_df.columns[3])  
print(iris_dropped.head())

   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0   1            5.1           3.5           0.2  Iris-setosa
1   2            4.9           3.0           0.2  Iris-setosa
2   3            4.7           3.2           0.2  Iris-setosa
3   4            4.6           3.1           0.2  Iris-setosa
5   6            5.4           3.9           0.4  Iris-setosa

In [10]:
import pandas as pd
data={
    "Employee_ID":[101,102,103,104,105],
    "Name":["Alice","Bob","Charlie","Diana","Edward"],
    "Department":["HR","IT","IT","Marketing","Sales"],
    "Age":[29,34,41,28,38],
    "Salary":[50000,70000,65000,55000,60000],
    "Years_of_Experience":[4,8,10,3,12],
    "Joining_Date":["2020-03-15","2017-07-19","2013-06-01","2021-02-10","2010-11-25"],
    "Gender":["Female","Male","Male","Female","Male"],
    "Bonus":[5000,7000,6000,4500,5000],
    "Rating":[4.5,4.0,3.8,4.7,3.5]
}
df=pd.DataFrame(data)
df.to_csv("employees.csv",index=False)

In [11]:
df.shape

(5, 10)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [13]:
df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [14]:
df.head()
df.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [16]:
print(df["Salary"].mean())      
print(df["Bonus"].sum())        
print(df["Age"].min())          
print(df["Rating"].max())

60000.0
27500
28
4.7

In [19]:
df.sort_values(by="Salary",ascending=False)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [21]:
def categorize_rating(rating):
    if rating>=4.5:
        return "Excellent"
    elif rating>=4.0:
        return "Good"
    else:
        return "Average"
df["Performance_Category"]=df["Rating"].apply(categorize_rating)
print(df[["Name", "Rating", "Performance_Category"]])

      Name  Rating Performance_Category
0    Alice     4.5            Excellent
1      Bob     4.0                 Good
2  Charlie     3.8              Average
3    Diana     4.7            Excellent
4   Edward     3.5              Average

In [22]:
df.isnull().sum()

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

In [24]:
df.rename(columns={"Employee_ID":"ID"},inplace=True)
df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [25]:
df[df["Years_of_Experience"]>5]     
df[df["Department"]=="IT"]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

In [27]:
df["Tax"]=df["Salary"]*0.10
df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

In [29]:
check_df=pd.read_csv("employees_modified.csv")
print(check_df)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Performance_Category     Tax
0  Female   5000     4.5            Excellent  5000.0
1    Male   7000     4.0                 Good  7000.0
2    Male   6000     3.8              Average  6500.0
3  Female   4500     4.7            Excellent  5500.0
4    Male   5000     3.5              Average  6000.0